name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  IMAGE_VERSION_MAJOR: 1
  IMAGE_VERSION_MINOR: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog Fly
        uses: jfrog/fly-action@v1
        with:
          url: https://cga.jfrog.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: cga.jfrog.io/docker/${{ github.repository }}:${{ env.IMAGE_VERSION_MAJOR }}.${{ env.IMAGE_VERSION_MINOR }}.${{ github.run_number }}
